type Roles {
  id: ID
  name: String
}
input IRole {
  id: ID
  name: String
}
type Query {
"""Response for Role"""
  getRole(id: ID, name: String): Roles
  getRoles: [Roles]
}

"""Response for Role"""
type RolePayload {
  success: Boolean
  message: String
}
type Mutation {
"""Response for user login"""
  createRoleMutation(input: IRole) : Roles
}